---
version: "2.1"
services:
  ubuntumate:
    image: linuxserver/webtop:ubuntu-mate
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/data:/config
    ports:
      - 3000:3000
    devices:
    restart: unless-stopped
